name: Raven-PI image build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: | 
          sudo apt update
          sudo apt-get -y install coreutils quilt parted qemu-user-static debootstrap zerofree zip \
          dosfstools bsdtar libcap2-bin grep rsync xz-utils file git curl
    - name: build the image
      run: |
          sudo ./build.sh -c raven-pi.config
    
    - uses: actions/upload-artifact@master
      with:
        name: raven-pi-image
        path: ${{ github.workspace }}/deploy
          # /home/runner/work/raven-pi/raven-pi/deploy/image_2019-11-08-raven-pi-lite.zip
          
